os: windows
language: node_js
node_js:
  - 12
mono: none
solution: Czeum.sln
install:
  - choco install dotnetcore-sdk
  - choco install opencover.portable
  - dotnet tool install --global Codecov.Tool
script:
  - dotnet restore
  - dotnet build
  - Opencover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -output:".\czeum_coverage.xml" -oldstyle
  - codecov -f "czeum_coverage.xml" -t 91b144ca-11c8-4483-beb4-8dbe24c2c429